// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3SVqPLIzueu2lCoriDUXvNftlvMgGeBY',
    appId: '1:779408576826:web:31a8adf7819a8d6ebf0003',
    messagingSenderId: '779408576826',
    projectId: 'sbazar-ce4b2',
    authDomain: 'sbazar-ce4b2.firebaseapp.com',
    storageBucket: 'sbazar-ce4b2.appspot.com',
    measurementId: 'G-EPJ2VNR9HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLV5_zvrgWvVwWEcb3eUqju70Y3VKaDHg',
    appId: '1:779408576826:android:a169aa18327d8f03bf0003',
    messagingSenderId: '779408576826',
    projectId: 'sbazar-ce4b2',
    storageBucket: 'sbazar-ce4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlgs2Bw3eZlH8F1z5jzJHh3cOux4500g',
    appId: '1:779408576826:ios:b894c130222c11a7bf0003',
    messagingSenderId: '779408576826',
    projectId: 'sbazar-ce4b2',
    storageBucket: 'sbazar-ce4b2.appspot.com',
    androidClientId: '779408576826-073ctkt9brg2mgehup22864vp5dvc8sg.apps.googleusercontent.com',
    iosClientId: '779408576826-6q41mhs0vmknlfj63vl4t3kaj2chrei1.apps.googleusercontent.com',
    iosBundleId: 'com.gmbh.sbazar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlgs2Bw3eZlH8F1z5jzJHh3cOux4500g',
    appId: '1:779408576826:ios:7160c5ad555cd2f9bf0003',
    messagingSenderId: '779408576826',
    projectId: 'sbazar-ce4b2',
    storageBucket: 'sbazar-ce4b2.appspot.com',
    androidClientId: '779408576826-073ctkt9brg2mgehup22864vp5dvc8sg.apps.googleusercontent.com',
    iosClientId: '779408576826-c9hvjmbirt51i1jici5gvroame1vkg9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.amberBird',
  );
}
